[build]
functions = "netlify/functions"  # Ruta al directorio de funciones

[build.environment]
NODE_VERSION = "18"  # Versión de Node.js que deseas usar

[build.command]
publish = "dist"  # Directorio de salida de tu aplicación, si es necesario

[[plugins]]
package = "@netlify/plugin-functions"
